name = "ImageInpainting"
uuid = "2bcd8d84-2ef9-5317-bfa0-0ed5605635ad"
author = "JÃºlio Hoffimann <julio.hoffimann@gmail.com>"
version = "0.2.0"

[deps]
CpuId = "adafc99b-e345-5852-983c-f28acb93d879"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
ImageMorphology = "787d08f9-d448-5407-9aad-5290dd7ab264"

[compat]
CpuId = "^0.2"
FFTW = "^1.0"
ImageFiltering = "^0.6"
ImageMorphology = "^0.2"
julia = "1"

[extras]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuartzImageIO = "dca85d43-d64c-5e67-8c65-017450d5d020"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"
VisualRegressionTests = "34922c18-7c2a-561c-bac1-01e79b2c4c92"

[targets]
test = ["Test", "Pkg", "ColorTypes", "ImageMagick", "Plots", "QuartzImageIO", "TestImages", "VisualRegressionTests"]
